version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./dev/django.prod.Dockerfile
    command: ["gunicorn", "danesfield.wsgi", "-w", "10", "--bind", "0.0.0.0:8000"]
    tty: true
    environment:
      DJANGO_CONFIGURATION: DevelopmentConfiguration
      DJANGO_DATABASE_URL: postgres://postgres:postgres@postgres:5432/django
      DJANGO_CELERY_BROKER_URL: amqp://rabbitmq:5672/
      DJANGO_MINIO_STORAGE_ENDPOINT: minio:9000
      DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
      DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
      DJANGO_STORAGE_BUCKET_NAME: django-storage
      DJANGO_MINIO_STORAGE_MEDIA_URL: http://localhost:9000/django-storage
    volumes:
      - .:/opt/django-project
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
      - minio
