# Generated by Django 3.2.7 on 2021-12-07 18:52

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def create_default_algorithm(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    DockerImage = apps.get_model('algorithms', 'DockerImage')  # noqa: N806
    Algorithm = apps.get_model('algorithms', 'Algorithm')  # noqa: N806

    # Create underlying danesfield image
    danesfield_image, _ = DockerImage.objects.get_or_create(
        id=1,
        name='Danesfield',
        image_id='kitware/danesfield',
    )

    # Create underlying kwiver image
    kwiver_image, _ = DockerImage.objects.get_or_create(
        id=2,
        name='KWIVER',
        image_id='kitware/kwiver',
    )

    # Create algorithms
    Algorithm.objects.get_or_create(
        id=1,
        name='Danesfield',
        docker_image=danesfield_image,
        entrypoint='/danesfield/docker-entrypoint.sh',
        command='python /danesfield/tools/run_danesfield.py input/config.ini',
        gpu=True,
    )

    Algorithm.objects.get_or_create(
        id=2,
        name='TeleSculptor',
        docker_image=kwiver_image,
        entrypoint='input/telesculptor.sh',
        gpu=True,
    )


def remove_default_algorithm(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    DockerImage = apps.get_model('rdoasis.algorithms', 'DockerImage')  # noqa: N806
    Algorithm = apps.get_model('rdoasis.algorithms', 'Algorithm')  # noqa: N806

    # Delete default docker images and algorithms
    DockerImage.objects.get(id=1, name='Danesfield').delete()
    Algorithm.objects.get(id=1, name='Danesfield').delete()
    DockerImage.objects.get(id=2, name='KWIVER').delete()
    Algorithm.objects.get(id=2, name='TeleSculptor').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_default_site'),
    ]

    operations = [
        migrations.RunPython(code=create_default_algorithm, reverse_code=remove_default_algorithm)
    ]
