# Generated by Django 3.2.7 on 2021-12-07 18:52

from django.db import migrations


def create_default_algorithm(apps, schema_editor):
    DockerImage = apps.get_model('algorithms', 'DockerImage')  # noqa: N806
    Algorithm = apps.get_model('algorithms', 'Algorithm')  # noqa: N806

    # Create underlying danesfield image
    danesfield_image, _ = DockerImage.objects.get_or_create(
        id=1,
        name='Danesfield',
        image_id='kitware/danesfield',
    )

    # Create algorithm
    Algorithm.objects.get_or_create(
        id=1,
        name='Danesfield',
        docker_image=danesfield_image,
        entrypoint='/danesfield/docker-entrypoint.sh',
        command='python /danesfield/tools/run_danesfield.py input/config.ini',
    )


def remove_default_algorithm(apps, schema_editor):
    DockerImage = apps.get_model('rdoasis.algorithms', 'DockerImage')  # noqa: N806
    Algorithm = apps.get_model('rdoasis.algorithms', 'Algorithm')  # noqa: N806

    # Delete default docker image and algorithm
    DockerImage.objects.get(id=1, name='Danesfield').delete()
    Algorithm.objects.get(id=1, name='Danesfield').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_default_site'),
    ]

    operations = [
        migrations.RunPython(code=create_default_algorithm, reverse_code=remove_default_algorithm)
    ]
