# Generated by Django 3.2.9 on 2021-11-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0004_alter_checksumfile_status'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='files',
            field=models.ManyToManyField(
                blank=True, related_name='image_datasets', to='rgd.ChecksumFile'
            ),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='point_cloud_file',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='imageless_datasets',
                to='rgd.checksumfile',
            ),
        ),
    ]
