# Generated by Django 3.2.7 on 2021-12-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_default_algorithm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetrun',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='datasetrun',
            name='output_files',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='DatasetRun',
        ),
    ]
